name: Publish plugin

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Write gradle.properties
      run: |
        mkdir -p $HOME/.gradle
        echo "gradle.publish.key=$GRADLE_PUBLISH_KEY" >> $HOME/.gradle/gradle.properties
        echo "gradle.publish.secret=$GRADLE_PUBLISH_SECRET" >> $HOME/.gradle/gradle.properties

    - name: Restore gradle.properties
      env:
        GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
        GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
      shell: bash
      run: |
        mkdir -p $HOME/.gradle/
        echo "gradle.publish.key=${GRADLE_PUBLISH_KEY}" >> ~/.gradle/gradle.properties
        echo "gradle.publish.secret=${GRADLE_PUBLISH_SECRET}" >> ~/.gradle/gradle.properties

    - name: Publish plugin
      uses: burrunan/gradle-cache-action@v1
      env:
        GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
        GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
      with:
        # If you have multiple jobs, use distinct job-id in in case you want to split caches
        # For instance, jobs with different JDK versions can't share caches
        # RUNNER_OS is added to job-id automatically
        job-id: jdk8
        # Specifies arguments for Gradle execution
        # If arguments is missing or empty, then Gradle is not executed
        arguments: publishPlugins
